## 目标：1.连接数据库 2.把数据读到pandas 3.初步查看数据结构

In [1]:
%%HTML
<style>
    body {
        --vscode-font-family: "Consolas", "思源黑体 CN"
    }
</style>

In [2]:
# 1. 导入库
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

# 2. 建立连接
engine = create_engine("postgresql://postgres:gxt20040705@localhost:5432/postgres")

# 3. 测试读取
df_raw = pd.read_sql("SELECT * FROM raw_sample LIMIT 1000", engine)

df_raw.head()

  user_id  time_stamp  adgroup_id          pid  clk    user  nonclk
0    None  1494137644           1  430548_1007    0  581738       1
1    None  1494638778           3  430548_1007    0  449818       1
2    None  1494650879           4  430548_1007    0  914836       1
3    None  1494651029           5  430548_1007    0  914836       1
4    None  1494302958           8  430548_1007    0  399907       1

In [3]:
#检查数据规模
pd.read_sql("SELECT COUNT(*) FROM raw_sample;", engine)

      count
0  26557961

In [4]:
pd.read_sql("SELECT COUNT(*) FROM ad_feature;", engine)

    count
0  846811

In [4]:
pd.read_sql("SELECT COUNT(*) FROM user_profile;", engine)

     count
0  1061768

In [5]:
#检查点击率是否正常
query = """
SELECT 
    COUNT(*) AS total_impressions,
    SUM(clk) AS total_clicks,
    SUM(clk)::float / COUNT(*) AS ctr
FROM raw_sample;
"""

pd.read_sql(query, engine)

   total_impressions  total_clicks       ctr
0           26557961       1366056  0.051437

In [6]:
#检查前1000行的数值情况
df_raw.isnull().sum()

user_id       1000
time_stamp       0
adgroup_id       0
pid              0
clk              0
user             0
nonclk           0
dtype: int64

In [7]:
#检查全部数值情况
query = """
SELECT 
    COUNT(*) FILTER (WHERE user IS NULL) AS user_null,
    COUNT(*) FILTER (WHERE adgroup_id IS NULL) AS ad_null,
    COUNT(*) FILTER (WHERE clk IS NULL) AS clk_null
FROM raw_sample;
"""

pd.read_sql(query, engine)

   user_null  ad_null  clk_null
0          0        0         0

In [8]:
#检查clk
pd.read_sql("SELECT DISTINCT clk FROM raw_sample;", engine)

   clk
0    0
1    1

In [6]:
pd.read_sql("""
WITH s AS (
  SELECT *
  FROM raw_sample TABLESAMPLE SYSTEM (1)
)
SELECT 
  COUNT(*) - COUNT(DISTINCT ("user", time_stamp, adgroup_id)) AS duplicate_count_sample
FROM s;
""", engine)

   duplicate_count_sample
0                       0