## 人群画像 CTR + 高价值用户识别

In [2]:
import sys
print(sys.executable)
# 基础库
import pandas as pd
import numpy as np

# 数据库
from sqlalchemy import create_engine

# 可视化（后面会用）
import matplotlib.pyplot as plt
import seaborn as sns
# 建立连接
engine = create_engine("postgresql://postgres:gxt20040705@localhost:5432/postgres")

d:\Anaconda\envs\project2\python.exe

In [7]:
# 年龄 vs CTR
pd.read_sql("""
SELECT 
    u.age_level,
    COUNT(*) AS impressions,
    SUM(r.clk) AS clicks,
    SUM(r.clk)::float / COUNT(*) AS ctr
FROM raw_sample r
JOIN user_profile u
ON r."user" = u.userid
GROUP BY u.age_level
ORDER BY ctr DESC;
""", engine)
# 不同年龄段用户的点击率存在明显差异，高年龄层（age_level=6）和部分低年龄层（age_level=1）点击意愿更强
# 而中间年龄段用户点击率相对较低，说明广告内容对不同年龄群体的吸引力存在差异。

   age_level  impressions  clicks       ctr
0          6       440429   24760  0.056218
1          1      1379703   76211  0.055237
2          0         9189     482  0.052454
3          5      4652618  242691  0.052162
4          2      4567837  236328  0.051737
5          3      7573614  386683  0.051057
6          4      6406045  317358  0.049540

In [8]:
# 消费能力 vs ctr
pd.read_sql("""
SELECT 
    u.pvalue_level,
    COUNT(*) AS impressions,
    SUM(r.clk) AS clicks,
    SUM(r.clk)::float / COUNT(*) AS ctr
FROM raw_sample r
JOIN user_profile u
ON r."user" = u.userid
GROUP BY u.pvalue_level
ORDER BY u.pvalue_level;
""", engine)
# 消费能力较高的用户（pvalue_level=3）点击率反而较低，
# 说明高价值用户对广告更加理性，不容易被泛化广告吸引；
# 而中低消费用户点击意愿更强，适合进行流量转化类广告投放。

   pvalue_level  impressions  clicks       ctr
0           1.0      4117894  211887  0.051455
1           2.0      6991303  359133  0.051369
2           3.0       895966   42277  0.047186
3           NaN     13024272  671216  0.051536

In [ ]:
# 性别 vs CTR
pd.read_sql("""
SELECT 
    u.final_gender_code,
    SUM(r.clk)::float / COUNT(*) AS ctr
FROM raw_sample r
JOIN user_profile u
ON r."user" = u.userid
GROUP BY u.final_gender_code;
""", engine)
# 不同性别用户点击率存在差异，其中某一性别群体CTR明显更高，
# 说明广告内容或商品类型可能更契合该用户群体偏好。

   final_gender_code       ctr
0                  1  0.048354
1                  2  0.052445

## 用户点击行为总结

1. 高点击用户特征：
   - 年龄段：6、1
   - 消费能力：中低等级（pvalue=1,2）
   - 性别：gender=2（女性）

2. 低点击用户特征：
   - 年龄段：4
   - 高消费人群（pvalue=3）

## 业务建议

- 优先向高CTR人群投放广告，提高点击转化率
- 针对高消费用户优化广告内容，提高精准度